name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          timeout: 15m  # Correct parameter name (not script_timeout)
          envs: StrictHostKeyChecking=no
          script: |
            # 1. Clean environment
            cd ~/devops-ci-cd
            rm -rf node_modules .next
            rm -f package-lock.json
            
            # 2. Update repository
            git config --global credential.helper '!f() { echo "username=git"; echo "password=${{ secrets.GITHUB_TOKEN }}"; }; f'
            git fetch --all
            git reset --hard origin/main
            
            # 3. Fix Node.js permissions
            sudo chown -R $USER:$GROUP ~/.npm
            sudo chown -R $USER:$GROUP ~/.config
            
            # 4. Install dependencies (use npm install instead of ci due to lockfile issues)
            npm install --force --no-audit
            
            # 5. Local Next.js installation
            npm install next
            
            # 6. Build and start
            npm run build
            pm2 delete next-app || true
            pm2 start "npm run start" --name "next-app"
            pm2 save
            
            # 7. Wait for app to start
            sleep 10
            curl -I http://localhost:3000 || echo "Health check failed - check PM2 logs"
            echo "✅ Deployment completed at $(date)"