name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script_timeout: 15m
          envs: StrictHostKeyChecking=no
          script: |
            # 1. Clean up previous installation
            cd ~/devops-ci-cd
            rm -rf node_modules
            rm -f package-lock.json
            
            # 2. Ensure proper Git setup
            git config --global credential.helper '!f() { echo "username=git"; echo "password=${{ secrets.GITHUB_TOKEN }}"; }; f'
            git reset --hard origin/main
            git pull origin main
            
            # 3. Install Node.js if missing
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            # 4. Clean npm cache and install
            npm cache clean --force
            npm ci --no-audit
            
            # 5. Global Next.js fallback
            if ! command -v next &> /dev/null; then
              npm install -g next
            fi
            
            # 6. Build and deploy
            npm run build
            pm2 delete next-app || true
            pm2 start "npm run start" --name "next-app"
            pm2 save
            pm2 list
            
            # 7. Verify deployment
            sleep 5
            curl -I http://localhost:3000 || echo "Health check failed - check PM2 logs"
            echo "✅ Deployment completed at $(date)"